[build]
  command = "npm install && node build.mjs"
  publish = "."

[[redirects]]
  from = "/"
  to = "/src/index.html"
  status = 200

[[redirects]]
  from = "/blog.html"
  to = "/src/blog.html"
  status = 200

[[redirects]]
  from = "/blog/:post"
  to = "/src/blog/:post"
  status = 200

[[redirects]]
  from = "/appointment.html"
  to = "/src/appointment.html"
  status = 200

